/*
 * base.h
 *
 *  Created on: Aug 28, 2025
 *      Author: DELL
 */

#ifndef BASE_H_
#define BASE_H_

#define PERIPHERAL_BASE							(0x40000000)

#define APB1_PERIPHERAL_OFFSET					(0x0000)
#define APB1_PERIPHERAL							(PERIPHERAL_BASE + APB1_PERIPHERAL_OFFSET)

#define APB2_PERIPHERAL_OFFSET					(0x00010000)
#define APB2_PERIPHERAL							(PERIPHERAL_BASE + APB2_PERIPHERAL_OFFSET)

#define AHB_PERIPHERAL_OFFSET					(0x00020000)
#define AHB_PERIPHERAL							(PERIPHERAL_BASE + AHB_PERIPHERAL_OFFSET)

#define GPIOA_PERIPHERAL_OFFSET					(0x00000000)
#define GPIOA_PERIPHERAL						(AHB_PERIPHERAL + GPIOA_PERIPHERAL_OFFSET)

#define GPIOB_PERIPHERAL_OFFSET					(0x00000400)
#define GPIOB_PERIPHERAL						(AHB_PERIPHERAL + GPIOB_PERIPHERAL_OFFSET)

#define GPIOC_PERIPHERAL_OFFSET					(0x00000800)
#define GPIOC_PERIPHERAL						(AHB_PERIPHERAL + GPIOC_PERIPHERAL_OFFSET)

#define USART2_PERIPHERAL_OFFSET				(0x00004400)
#define USART2_PERIPHERAL						(APB1_PERIPHERAL + USART2_PERIPHERAL_OFFSET)

#define ADC_PERIPHERAL_OFFSET					(0x00002400)
#define ADC_PERIPHERAL							(APB2_PERIPHERAL + ADC_PERIPHERAL_OFFSET)

#define RCC_PERIPHERAL_OFFSET					(0x00003800)
#define RCC_PERIPHERAL							(AHB_PERIPHERAL + RCC_PERIPHERAL_OFFSET)

#define FLASH_PERIPHERAL_OFFSET					(0x00003C00)
#define FLASH_PERIPHERAL						(AHB_PERIPHERAL + FLASH_PERIPHERAL_OFFSET)



enum State {
    OFF = 48,   //int 48 ascii 0
    ON = 49     //int 49 ascii 1
};



#endif /* BASE_H_ */
